# Build settings
name: Rob Bos
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-cayman
plugins:
  - jemoji
  - jekyll-paginate
tag_archive:
  type: liquid
  path: /tags/